##⇘⇘Ci-dessous les raccourcis enrichis reposant sur le script inputevent.lua
## '#event:click' désigne l'action d'un appui simple sur la touche, '#event:double_click' celle d'un double appui, '#event:press' celle d'un appui long, '#event:release' celle du relâchement après un appui long
## Pour les autres actions disponibles, se reporter à la documentation du projet amont : https://github.com/zhongfly/InputEvent/tree/property-expansion
##! Attention : toutes les touches ne disposent pas de l'ensemble de ces actions
## Le script permet aussi de déclencher des commandes différentes pour une même action selon une condition, dont la syntaxe est celle de profile-cond (la condition des profils automatiques)
## La syntaxe devient donc '#event:action|condition' (un '#event:action' sans condition s'exécute inconditionnellement) ; les commandes sont évaluées de bas en haut, la première dont la condition est remplie est exécutée
## Ces touches ont aussi une ligne dans input.conf (affichage du raccourci dans le menu uosc) : modifier les deux fichiers

RIGHT           seek 5                                        #event:click
RIGHT           script-message-to evafast speedup             #event:press
RIGHT           script-message-to evafast slowdown            #event:release

TAB             script-message-to uosc playlist               #event:click
TAB             script-message-to uosc toggle-ui              #event:press
TAB             script-message-to uosc toggle-ui              #event:release

PGDWN           add chapter -1                                                                    #event:click
PGDWN           playlist-prev;show-text "Liste de lecture : ${playlist-pos-1}/${playlist-count}"  #event:click|chapter == 0
PGDWN           playlist-prev;show-text "Liste de lecture : ${playlist-pos-1}/${playlist-count}"  #event:click|chapters == 0
PGDWN           playlist-prev;show-text "Liste de lecture : ${playlist-pos-1}/${playlist-count}"  #event:press
PGUP            add chapter  1                                                                    #event:click
PGUP            playlist-next;show-text "Liste de lecture : ${playlist-pos-1}/${playlist-count}"  #event:click|chapter+1 == chapters
PGUP            playlist-next;show-text "Liste de lecture : ${playlist-pos-1}/${playlist-count}"  #event:click|chapters == 0
PGUP            playlist-next;show-text "Liste de lecture : ${playlist-pos-1}/${playlist-count}"  #event:press

SPACE           cycle pause;script-message-to uosc flash-pause-indicator  #event:click
SPACE           script-binding simplehistory/history-load-last            #event:click|idle_active

MBTN_LEFT       ignore                                                    #event:click
MBTN_LEFT       cycle fullscreen                                          #event:double_click
