# Fichier de configuration servant à remplir la propriété de menu `menu-data` du script select.lua interne à mpv
# Laissé vide afin d'éviter tout conflit avec les fonctionnalités du script personnalisé dyn_menu.lua
