# Intervalle, en secondes, entre deux enregistrements automatiques de la progression et de l'état de lecture. Par défaut : 60 secondes
save_interval=60
# Pourcentage de progression au-delà duquel la progression et l'état de lecture du fichier sont automatiquement supprimés. Par défaut : 99
percent_pos=99