# Indiquer manuellement le chemin absolu des exécutables si les programmes suivants ne sont pas dans le PATH

# 1. ffmpeg
#ffmpeg_path=C:/Program Files/ffmpeg/bin/ffmpeg.exe
ffmpeg_path=ffmpeg

# 2. ffsubsync
#ffsubsync_path=C:/Program Files/ffsubsync/ffsubsync.exe
#ffsubsync_path=/home/user/.local/bin/ffsubsync

# 3. alass
#alass_path=C:/Program Files/ffmpeg/bin/alass.exe
#alass_path=/usr/bin/alass
##⇘⇘Le chemin ci-dessous fait chercher le programme dans le dossier racine de mpv
alass_path=alass

# Outil de synchronisation des sous-titres préféré. Valeurs autorisées : 'ffsubsync', 'alass', 'ask'.
# Avec « ask », le script demande à chaque fois quel outil utiliser :

# 1. Outil préféré pour la synchronisation sur l'audio. ('ffsubsync','alass','ask')
audio_subsync_tool=alass

# 2. Outil préféré pour la synchronisation sur un autre sous-titre. ('ffsubsync','alass','ask')
altsub_subsync_tool=alass

# Désactiver le sous-titre d'origine (yes,no)
# Une fois la synchronisation terminée, demande à mpv d'ignorer la piste de sous-titres d'origine
unload_old_sub=no