###Les commentaires en fin de ligne d'option ne sont pas pris en charge, écrivez-les sur une ligne distincte

##Désactiver toutes les fonctions de chargement automatique. Par défaut : no
#disabled=yes

##Charger automatiquement dans la liste de lecture toutes les images du dossier courant (sous-dossiers exclus). Par défaut : yes
#images=no

##Charger automatiquement dans la liste de lecture toutes les vidéos du dossier courant (sous-dossiers exclus). Par défaut : yes
#videos=no

##Charger automatiquement dans la liste de lecture tous les fichiers audio du dossier courant (sous-dossiers exclus). Par défaut : yes
#audio=no

##Liste blanche d'extensions d'images, de vidéos et de fichiers audio supplémentaires à prendre en compte
additional_image_exts=jfif
additional_video_exts=asf,f4v,rm,ts,vob
additional_audio_exts=dsf,spx

##<auto|recursive|lazy|ignore par défaut> À l'ouverture d'un fichier, parcourir les sous-dossiers de façon récursive, paresseuse, ou les ignorer tous
directory_mode=ignore

##Ignorer les fichiers cachés. Par défaut : yes
#ignore_hidden=no

##Motifs de noms de fichiers à ignorer, séparés par des virgules. Vide par défaut
##Les motifs Lua sont acceptés ; % permet d'échapper les caractères
#ignore_patterns=^~,^bak-,%.bak$

#Ne charger automatiquement que les fichiers du même type (vidéo, audio, image). Par défaut : no
same_type=yes

#Ne charger automatiquement que les fichiers d'une même série. Par défaut : no
#same_series=yes