# Il suffit de définir soit la liste noire, soit la liste blanche

# Liste blanche : n'autoriser que les formats vidéo
#whitelist=3gp,amr,amv,asf,avi,avi,bdmv,f4v,flv,ifo,iso,m2ts,m4v,mkv,mov,mp4,mpeg,mpg,ogv,rm,rmvb,ts,vob,webm,wmv

# Ou bien, liste noire des formats que l'on trouve souvent à côté des vidéos
blacklist=mpls,mks,mka,weba,aqt,ass,gsub,idx,jss,lrc,mks,pgs,pjs,psb,rt,slt,smi,sub,sup,sbv,srt,ssa,ssf,ttxt,txt,usf,vt,vtt

remove_files_without_extension=yes

# Le script n'agit qu'au démarrage de la lecture ; désactivez cette option pour qu'il agisse aussi à chaque modification de la liste de lecture
oneshot=no
