#Active la lecture et le chargement automatiques des fichiers de chapitres externes. Par défaut : yes
autoload=yes
#Active l'exportation automatique du fichier de chapitres (lorsque les informations de chapitre changent). Par défaut : no
autosave=no
#Utilise les informations de chapitres externes pour écraser les informations de chapitres internes de la vidéo. Par défaut : no
force_overwrite=no
#Spécifie l'identifiant et l'extension du fichier de chapitres externe
chapter_file_ext=.chp
#Choisit si le fichier de chapitres externe doit correspondre à l'extension du fichier source. Par défaut : yes
basename_with_ext=yes
#Lit le fichier de chapitres externe depuis un sous-répertoire spécifié situé dans le même dossier que le fichier vidéo
#Remarque : le script lit en priorité le fichier de chapitres externe depuis le sous-répertoire spécifié
#Si le fichier n'existe pas dans le sous-répertoire, le script tentera ensuite de le lire dans le même dossier que le fichier vidéo
external_chapter_subpath=chapters
#Stocke uniformément les fichiers de chapitres dans le répertoire global configuré ; les fichiers réseau utiliseront toujours le répertoire global. Par défaut : no
global_chapters=no
#Spécifie le chemin du répertoire global des fichiers de chapitres. Peut être un chemin relatif ou absolu pris en charge par mpv
global_chapters_dir=~~/files/chapters
#Utilise une valeur de hachage pour enregistrer le nom du fichier de chapitres dans le répertoire global. Par défaut : no
##Si défini sur 'no', le fichier de chapitres sera nommé d'après le fichier multimédia correspondant, ce qui peut provoquer des conflits
##L'utilisation du hachage évite que des fichiers multimédias de même nom situés dans des répertoires différents n'obtiennent le même fichier de chapitres
##Mais si vous déplacez le fichier vers un autre répertoire, la valeur de hachage changera, ce qui empêchera le chargement du fichier de chapitres
hash=no
#Définit si la saisie de renommage s'ouvre par défaut lors de la création d'un nouveau chapitre. Par défaut : yes
ask_for_title=yes
#Définit le nom d'espace réservé utilisé lors de la demande du titre d'un nouveau chapitre
placeholder_title=Chapter 
#Définit si la lecture est mise en pause lors de la demande du titre du chapitre. Par défaut : yes
pause_on_input=yes