###Ce fichier n'accepte pas les commentaires en fin de ligne d'option, écrivez-les sur une ligne distincte

# Enregistrer l'historique des commandes dans un fichier et le recharger. Par défaut : no
persist_history=yes
# Chemin du fichier d'historique des commandes. Par défaut : ~~state/command_history.txt
history_path=~~/files/command_history.txt