###Cette configuration ne prend pas en charge les commentaires après une option ; ils doivent être placés sur une nouvelle ligne

# Spécifie la police à chasse fixe utilisée par la console pour afficher l'autocomplétion. Dans les autres cas, --osd-font est utilisé
monospace_font=Noto Sans Mono CJK SC
# Taille de police, 24 par défaut. La taille finale sera multipliée par le facteur d'échelle
#font_size=24
# Définit la taille du contour de la police utilisée pour le REPL et la console. Valeur par défaut : 1.32
border_size=1.3
# Opacité de l'arrière-plan du menu. Va de 0 (opaque) à 255 (totalement transparent). Valeur par défaut : 80
background_alpha=50
# Espace entre les éléments du menu, exprimé en pourcentage de la taille de police. Valeur par défaut : 0.2
#gap=0.2
# Marge intérieure du menu. Valeur par défaut : 10
#padding=10
# Taille du contour du menu. Valeur par défaut : 0
#menu_outline_size=0
# Couleur du contour du menu. Valeur par défaut : #FFFFFF
#menu_outline_color=#FFFFFF
# Rayon des coins arrondis du menu. Valeur par défaut : 8
#orner_radius=8
# Couleur de l'élément sélectionné dans le menu. Valeur par défaut : #222222
#selected_color=#222222
# Couleur d'arrière-plan de l'élément sélectionné dans le menu. Valeur par défaut : #FFFFFF
#selected_back_color=#FFFFFF
# Couleur des caractères correspondant à la chaîne de recherche. Valeur par défaut : #0088FF
#match_color=#0088FF
# Utilise la hauteur de la fenêtre pour mettre à l'échelle la console. Peut valoir yes, no ou auto, selon l'option --osd-scale-by-window. Valeur par défaut : auto
#scale_with_window=auto
# Utilise une recherche exacte plutôt qu'une recherche floue lors des requêtes. Valeur par défaut : no
# Faire précéder la requête du caractère ' force l'activation de la correspondance exacte
#exact_match=no
# Définit si l'autocomplétion par Tab est sensible à la casse. S'applique uniquement aux caractères ASCII
## Valeur par défaut : no sous Windows, yes sur les autres plateformes
#case_sensitive=no
# Supprime les entrées en double dans l'historique afin de ne conserver que les plus récentes. Par défaut : yes
history_dedup=yes
# Définit le rapport entre la hauteur et la largeur de la police, pour ajuster la largeur du tableau des suggestions de complétion. Valeur par défaut : auto
## Une valeur comprise entre 1.8 et 2.5 est utile pour les polices à chasse fixe courantes
#font_hw_ratio=auto