###Les commentaires en fin de ligne d'option ne sont pas pris en charge, écrivez-les sur une ligne distincte
###Aucune espace superflue n'est autorisée entre l'option et sa valeur
## https://mpv.io/manual/master/#context-menu
# Taille de la police
font_size=20
# Espacement entre les entrées du menu
gap=0.2
# Marges horizontale et verticale des entrées du menu
padding_x=8
padding_y=4
# Épaisseur et couleur de la bordure des entrées du menu
menu_outline_size=0.5
menu_outline_color=#FFFFFF
# Rayon des coins arrondis
corner_radius=5
# Mettre le menu à l'échelle en fonction de la hauteur de la fenêtre. <no|yes|auto par défaut>
scale_with_window=auto
# Couleur du texte et du fond de l'entrée sélectionnée
focused_color=#222222
focused_back_color=#FFFFFF
# Couleur des entrées désactivées et des séparateurs
disabled_color=#555555
# Délai avant l'ouverture et la fermeture des sous-menus
seconds_to_open_submenus=0.2
seconds_to_close_submenus=0.2
