##! Attention : ce script de menu ne fonctionne que sous Windows
## Utiliser ou non l'implémentation interne du menu contextuel de mpv. Par défaut : yes
## Nécessite une version de mpv incluant le commit amont https://github.com/mpv-player/mpv/commit/3c1e983
use_mpv_impl=yes
### Activer ou non la prise en charge de la syntaxe de menu d'uosc. Incompatible avec la syntaxe de menu mpv.net prise en charge par défaut, mais permet d'utiliser celle d'uosc. Par défaut : no
uosc_syntax=yes
## Activer ou non l'échappement des titres de menu. Par défaut : yes
escape_title=yes
## Longueur maximale d'un titre de menu. Par défaut : 80. Au-delà, le titre est tronqué
## 0 signifie aucune limite de longueur
max_title_length=80
## Nombre maximal d'entrées du menu de la liste de lecture. Par défaut : 20
## 0 désactive le menu de la liste de lecture
max_playlist_items=20