# [0-4] 0 désactivé, 1 à la demande, 2 démarrage unique, 3 automatique manuel, 4 démarrage automatique
mode=3
# Délai en secondes utilisé pour sauter l'introduction (s'applique au mode 2)
start_delay=0
# Secondes
prevent_change_timer=30
# [0-3], désactivé quand "prevent_change_timer = 0". 0 désactivé, 1 conserver le maximum, 2 conserver le minimum, 3 conserver le plus récent
prevent_change_mode=0
# Tente, en ajustant geometry, d'éviter le comportement par défaut qui redimensionne la fenêtre à la taille de la source lorsque le filtre de recadrage change en mode fenêtré/maximisé
## 0 : ne pas corriger (recommandé), 1 : corriger - conserver la taille de la fenêtre 2 : corriger - conserver la largeur de la fenêtre, 3 : corriger - conserver la hauteur de la fenêtre. Valeur par défaut : 1
fix_windowed_behavior=0
# Secondes. 0 est la valeur minimale, soit 1 image. Valeur par défaut : 0.2
fast_change_timer=0.2
# Secondes. 0 désactive. Valeur par défaut : 0.5
limit_timer=0.5
# Secondes. Valeur par défaut : 2
ratio_timer=2
# Secondes. >='ratio_timer'. Valeur par défaut : 20, nouveau décalage pour les vidéos asymétriques
offset_timer=20
# Secondes, >='offset_timer', désactivé:0. Valeur par défaut : 40, absent de la liste des ratios, éventuellement avec un nouveau décalage
fallback_timer=40
# Entier, mis à l'échelle avec detect_round pour correspondre à la largeur/hauteur de la source
linked_tolerance=2
# Liste séparée par des espaces
ratios=2.76 2.55 24/9 2.4 2.39 2.35 2.2 2.1 2 1.9 1.85 16/9 5/3 1.5 1.43 4/3 1.25 9/16 9/18 9/21
# Nombre pair, ajusté pour faciliter la correspondance avec la liste des ratios. Valeur par défaut : 2
ratio_tolerance=2
# [0-2], par défaut 0 désactivé, 1 fast_change_timer, 2 ratio_timer
read_ahead_mode=0
# Entier/images, augmente l'avance. Valeur par défaut : 0
read_ahead_sync=0
# [0.0-1] %, utilise un temps supplémentaire pour permettre aux nouvelles métadonnées d'être fractionnées plutôt que continues. 0 n'accepte que des métadonnées continues (strict), ce qui désactive cette option
segmentation=0.5
# Spécifie la méthode utilisée pour appliquer le recadrage : 0 lavfi-crop (ffmpeg/filter), 1 video-crop (mpv/VO). Valeur par défaut : 1
crop_method=1
# Filtre, voir https://ffmpeg.org/ffmpeg-filters.html#cropdetect
## Correspond à la valeur maximale utilisée ; si un noir peu profond est présent, augmentez-la progressivement
detect_limit=26
# Nombre pair
detect_round=2
# Débogage
debug=no