# Amplitude du déplacement lors de l'appui sur les touches du script
seek_distance=5

# Incrément de vitesse de lecture, appliqué à chaque 'speed_interval' jusqu'à atteindre la limite
speed_increase=0.1
speed_decrease=0.1

# Intervalle auquel l'incrément de vitesse est appliqué
speed_interval=0.05

# Vitesse de lecture maximale
speed_cap=3

# Vitesse de lecture maximale lorsque des sous-titres sont affichés ; 'no' revient à utiliser 'speed_cap'
subs_speed_cap=1.5

# Multiplier la vitesse actuelle par l'incrément avant l'ajustement (accélération exponentielle). Par défaut : no
# Utilisez alors des valeurs bien plus faibles que celles par défaut, par exemple speed_increase=0.05, speed_decrease=0.025
multiply_modifier=no

# Afficher la vitesse actuelle sur l'OSD (avec uosc, la vitesse clignote). Par défaut : yes
show_speed=yes

# Afficher la vitesse actuelle sur l'OSD lors d'un changement de vitesse (avec uosc, la vitesse clignote). Par défaut : yes
show_speed_toggled=yes

# Afficher les déplacements sur l'OSD (avec uosc, la barre de progression clignote). Par défaut : yes
show_seek=yes

# Anticiper la lecture pour rendre les transitions plus douces lorsque 'subs_speed_cap' est défini. Par défaut : no
subs_lookahead=no

# Symboles affichés dans les messages OSD ; l'exemple correspond aux valeurs par défaut
#osd_symbol={\fnmpv-osd-symbols} {\r}
#osd_rewind={\fnmpv-osd-symbols} {\r}