# Spécifie le mode de fonctionnement du script ; trois modes sont disponibles : noth, pass, switch. Valeur par défaut : noth
## noth : ne fait rien
## pass : transmet le signal HDR pour le contenu HDR lorsque l'écran est en mode HDR
## switch : bascule automatiquement l'écran entre le mode HDR et le mode SDR selon le contenu vidéo lu par mpv ; disponible sous Windows 10 et versions ultérieures
#! Le mode pass n'est recommandé que pour les versions de mpv antérieures à v0.41.0 ; les versions suivantes prennent en charge le pass HDR par défaut, sans configuration supplémentaire
hdr_mode=noth
# Spécifie si le basculement automatique du mode HDR doit se faire uniquement en plein écran ou fenêtre maximisée. Ne s'applique que si hdr_mode=switch. Valeur par défaut : no
fullscreen_only=no
# Spécifie le pic de luminosité cible de votre écran HDR. Valeur par défaut : 0
# Par défaut, utilise la propriété d'information de pic de luminosité de l'écran fournie par display-info.dll : « user-data/display-info/max-luminance »
# Vous pouvez également indiquer une valeur spécifique pour outrepasser la détection interne
#! Rappel : si vous personnalisez cette option, vous devez indiquer la luminosité de pic réelle de l'écran, sinon le contenu HDR s'affichera incorrectement
target_peak=0
# Spécifie la valeur du contraste maximal de votre écran HDR
# Valeur par défaut : auto, qui tente de calculer la valeur correcte à partir de la propriété de niveau de noir de l'écran fournie par display-info.dll : « user-data/display-info/min-luminance »
#! Rappel : si vous personnalisez cette option, vous devez indiquer le contraste maximal réel de l'écran, sinon la compensation du niveau de noir ne pourra pas être appliquée correctement
## Par exemple, 100000 signifie que le contraste maximal de l'écran est de 100000:1
## Pour un écran OLED, vous pouvez indiquer la valeur spéciale inf pour appliquer un contraste infini
target_contrast=auto