## Activer ou non les fonctions du script. Par défaut : yes
enabled=yes
## Langue des messages OSD du script. Par défaut : eng
language=chs
## Durée d'affichage des messages OSD du script, en secondes. Par défaut : 15
timeout=15
## Délai avant l'enregistrement de la position, en millisecondes
#save_period=30
## Chemin d'enregistrement des fichiers de position de lecture par dossier vidéo
## Utilisez '/:dir%mpvconf%' ou '~~/' pour désigner le dossier portable_config, ou '/:dir%script%' pour le dossier du script
## Vous pouvez aussi utiliser '/:var' pour une variable d'environnement, par exemple '/:var%APPDATA%' ou '/:var%HOME%', ou encore indiquer directement un chemin absolu
history_dir=/:var%APPDATA%/mpv/files/historybookmarks
## Extension des fichiers de position de lecture par dossier
bookmark_ext=.mpv.history
## Nommer les fichiers de position à partir d'un hachage du dossier lu. Par défaut : yes
hash=yes
## Utiliser ou non les informations de la liste de lecture ; si désactivé, elles sont déduites du dossier contenant le fichier lu. Par défaut : yes
use_playlist=yes
## Liste blanche des extensions recherchées dans les dossiers
whitelist=3gp,amr,amv,asf,avi,avi,bdmv,f4v,flv,m2ts,m4v,mkv,mov,mp4,mpeg,mpg,ogv,rm,rmvb,ts,vob,webm,wmv
## Ne créer des fichiers d'historique que dans les chemins/dossiers indiqués
#included_dir=[]
## Chemins/dossiers des disques partagés (montés) à ignorer. Exemple Windows : excluded_dir=["X:", "Z:", "F:/Download/", "Download"]
#excluded_dir=[]