#Utiliser un fichier de configuration externe pour définir les actions de touches enrichies. Par défaut : no
enable_external_config=yes
#Chemin du fichier de configuration externe ; chemin relatif ou absolu accepté par mpv
#Attention : si vous activez cette fonction, assurez-vous que le fichier existe bien
external_config=~~/inputevent_key.conf
#Préfixe d'identification des événements de touches. Par défaut : event
prefix=event