##Format de l'image animée produite par ffmpeg ; au choix : webp, gif (par défaut)
#type=webp
#Chemin absolu de ffmpeg, ou bien placez-le dans le PATH
#ffmpeg_path=ffmpeg
#Dossier de sortie. Par défaut : ~~desktop/
dir=~~/files/animated
#Résolution de sortie ; longueur par défaut : 600
#rez=1280
#Fréquence d'images de sortie. Par défaut : 15
#fps=24
#0 par défaut (avec pertes) ; 1 pour du sans perte. En sans perte, ce n'est plus la qualité qui est fixée mais l'efficacité de l'encodage. Propre au webp
lossless=0
#Niveau de qualité en pourcentage, qui détermine la qualité du webp. Éviter de descendre sous 85. Propre au webp
quality=85
#6 par défaut. L'opération peut prendre un certain temps ; abaissez cette valeur si vous ne voulez pas attendre, mais plus elle est basse, plus le fichier est volumineux. Propre au webp
compression_level=3
#Nombre de répétitions de l'animation ; 0 par défaut, soit une boucle infinie
loop=0