##Adresse HTTP de TorrServer ; l'exemple correspond à la valeur par défaut
server=http://localhost:8090
##Activer ou non l'initialisation de TorrServer. Par défaut : no
#! N'activez cette option que si TorrServer est installé sur la même machine et n'est pas lancé automatiquement
torrserver_init=no
##Chemin de TorrServer ; l'exemple correspond à la valeur par défaut. Chemin relatif (si le PATH est configuré) ou absolu
##TorrServer doit être installé par vos soins, voir : https://github.com/YouROK/TorrServer
#! Cette option n'est utile que si torrserver_init=yes
torrserver_path=TorrServer
##Rechercher ou non les éventuelles pistes externes (audio, sous-titres). Par défaut : yes
search_for_external_tracks=yes