##Chemin absolu de ffmpeg, ou bien placez-le dans le PATH
##ffmpeg_path=ffmpeg
##Dossier de sortie. Par défaut : ~~screenshots/
screenshot_dir=~~/files/screenshots
##Capturer dans un format sans perte. Par défaut : no
lossless=no
