## Taille de la fenêtre PiP ; syntaxe décrite ici : https://mpv.io/manual/stable/#options-autofit
## Par exemple : 25%x25% 400x300
autofit=25%x25%
## Valeur d'autofit-larger rétablie à la sortie du mode incrustation d'image. De préférence identique à l'option --autofit-larger de mpv.conf. Par défaut : 100%x100%
autofit_restore_larger=100%x100%
## Valeur d'autofit-smaller rétablie à la sortie du mode incrustation d'image. De préférence identique à l'option --autofit-smaller de mpv.conf. Par défaut : 40%x30%
autofit_restore_smaller=40%x30%
## Position de la fenêtre en mode incrustation d'image (PiP). Par défaut : 100%:100% (en bas à droite). Syntaxe décrite ici : https://mpv.io/manual/stable/#options-geometry
geometry=100%:100%
## Position de la fenêtre à la sortie du mode incrustation d'image. Par défaut : 50%:50% (centrée)
geometry_restore=50%:50%
## Délai, en secondes, avant l'application de la position de la fenêtre, afin d'éviter tout problème de concurrence
geometry_delay=0.05