#Activer ou non les fonctions du script. Par défaut : yes
#! Attention : cette option peut être modifiée en cours d'exécution
enabled=yes
#Chemin du fichier où le script recentmenu (extension uosc) enregistre l'historique des lectures récentes. Chemin relatif ou absolu accepté par mpv
path=~~/files/recent.json
#Titre affiché en tête du menu du script
title=Lecture récente
#Nombre maximal d'entrées conservées dans l'historique des lectures récentes. Par défaut : 10
length=20
#Limite de caractères des entrées du menu des lectures récentes d'uosc. Par défaut : 88
width=70
#N'enregistrer que la dernière entrée lue parmi les fichiers d'une même série dans un même dossier. Par défaut : yes
#Lorsque cette option est active, seule la dernière lecture d'une même série d'un même dossier est conservée. La détection repose sur une mesure de similarité et peut se tromper
ignore_same_series=yes