###Ce fichier n'accepte pas les commentaires en fin de ligne d'option, écrivez-les sur une ligne distincte

# Format de date des entrées d'historique. Transmis tel quel à os.date de Lua
# Il s'agit du même format que celui de strftime(3)
history_date_format=%Y-%m-%d %H:%M:%S
# N'afficher que la dernière entrée d'historique pour un même chemin. Par défaut : yes
hide_history_duplicates=yes
# Chemin du fichier de configuration du menu intégré. Par défaut : ~~/menu.conf
menu_conf_path=~~/menu.conf
# Nombre maximal d'entrées de la liste de lecture affichées dans le menu. Par défaut : 25
#max_playlist_items=25
# Surveiller les propriétés référencées dans `menu.conf` et mettre à jour `menu-data`. Par défaut : yes
populate_menu_data=no