#Chemin absolu de ffmpeg, ou bien placez-le dans le PATH
#ffmpeg_path=ffmpeg
#Dossier d'enregistrement des extraits vidéo découpés
target_dir=~~/files/cutfragments
overwrite=yes
vcodec=copy
acodec=copy
debug=no