#Adresse du service fournissant les segments sponsorisés pour YouTube
#youtube_sponsor_server=https://sponsor.ajay.app/api/skipSegments
#Adresse du service fournissant les segments sponsorisés pour bilibili
#bilibili_sponsor_server=https://bsbsb.top/api/skipSegments
#Catégories de segments à récupérer et à sauter
#categories="sponsor"