# Jeton d'API, à récupérer depuis votre espace personnel après création d'un compte sur https://assrt.net
#L'exemple correspond à la clé prédéfinie dans le script
#api_token=tNjXZUnOJWcHznHDyalNMYqqP6IdDdpQ
# Utiliser https. Par défaut : yes
#use_https=no
# Configuration du proxy
#proxy=