# Chemin de l'exécutable faster-whisper, prend en charge les chemins absolus et relatifs
# Peut être téléchargé ici : https://github.com/Purfview/whisper-standalone-win
#fast_whisper_path=faster-whisper
# Spécifie le modèle à utiliser. Modèles disponibles : base, small，medium, large, turbo
#model=large-v3
# Spécifie le périphérique à utiliser. Périphériques disponibles : cpu、cuda
#device=cuda
# Spécifie le type de calcul à utiliser. Types disponibles : default,auto,int8,int8_float16,int8_float32,int8_bfloat16,int16,float16,float32,bfloat16
#compute_type=default
# Spécifie la langue de la transcription vocale ; laisser vide pour une détection automatique
#language=ja
# Spécifie le nombre de threads CPU à utiliser
# Valeur par défaut 0, détection automatique, avec un maximum de 4 threads
#threads=8
# Nombre maximal de caractères par ligne avant retour à la ligne
max_line_width=100
# Spécifie le chemin de sortie, prend en charge les chemins absolus et relatifs
# Valeur spéciale : « source » enregistre le fichier de sous-titres dans le répertoire du fichier vidéo
output_path=source
# Spécifie le nombre de sous-titres générés avant une mise à jour. Permet d'éviter un clignotement trop fréquent des sous-titres
update_interval=20
# Utilise une méthode de segmentation pour la transcription vocale, ce qui accélère considérablement l'initialisation des sous-titres
# Mais cela réduit la précision de la génération des sous-titres ainsi que la vitesse globale ; convient davantage aux vidéos longues
#! Depends on FFmpeg
use_segment=no
# Durée du segment, en secondes
segment_duration=10
## Options de l'API GPT ###
# Compatible avec toute API d'IA ayant la même structure que l'API GPT
# Modèle d'IA gratuit recommandé de Zhipu GLM : glm-4-flash
api_url=https://open.bigmodel.cn/api/paas/v4/chat/completions
# La clé API doit être demandée par vous-même depuis votre compte personnel sur la plateforme d'IA correspondante
api_key=
# Spécifie le modèle d'IA à utiliser
api_mode=glm-4-flash
api_temperature=0.95
# Débit d'utilisation de l'API par minute. Voir la documentation de l'API correspondante pour plus de détails
api_rate=15
# Spécifie la langue cible de la traduction par IA
translate=Chinese
# Spécifie la police utilisée pour les sous-titres ass générés
font_name=Noto Sans CJK SC