#Chemin absolu de ffmpeg, ou bien placez-le dans le PATH
ffmpeg_path=ffmpeg
#Langue des textes affichés par le script sur l'OSD et dans la console ; eng=anglais, chs=chinois. Par défaut : eng
language=chs