# Les options sont des listes de mots et de langues séparées par des barres obliques
##Active le script, oui par défaut
enabled=yes
##Synchronise la sélection des pistes, fonctionne mieux avec d'autres scripts, oui par défaut
hook=yes
##Imite les informations de liste de pistes de mpv afin de conserver la piste choisie par l'utilisateur dans le fichier, non par défaut
#fingerprint=yes
##Outrepasse la sélection explicite de piste de l'utilisateur, non par défaut
#force=yes
##Mémorise et hérite lors des lectures suivantes de la correspondance de piste choisie manuellement par l'utilisateur, non par défaut
smart_keep=yes

##Réglages de filtrage de la piste vidéo. Séparés par '/', prend en charge la syntaxe des expressions régulières Lua
#preferred_video_lang=
#excluded_video_words=
#expected_video_words=

##Réglages de filtrage de la piste audio. Séparés par '/', prend en charge la syntaxe des expressions régulières Lua
preferred_audio_lang=japanese/j[ap]n?/english/en%-us/eng?
preferred_audio_channels=8/6/3/2
excluded_audio_words=commentary/cast/staff/dub/guide
expected_audio_words=

##Réglages de filtrage de la piste de sous-titres. Séparés par '/', prend en charge la syntaxe des expressions régulières Lua
###La logique de sélection précise est la suivante : exclure d'abord les pistes correspondant à excluded_sub_words,
###puis tenter un score de correspondance selon la priorité de expected_sub_words ; en cas d'égalité, sélectionner selon la priorité de preferred_sub_lang
###si aucune correspondance n'est trouvée, continuer à tenter un score de correspondance selon la priorité de preferred_sub_lang
###dans tous les scores de priorité ci-dessus, les pistes externes obtiennent toujours un score de priorité plus élevé
###enfin, si toujours aucune correspondance, la sélection est confiée à la logique interne de sélection de piste de mpv
preferred_sub_lang=chs/sc$/zh%-cn/zh%-Hans/cht/tc$/zh%-Hant/zh%-hk/zh%-tw/chi/zho?
excluded_sub_words=sing/song/comment/danmaku/danmu/xml/弹幕
expected_sub_words=chs&j[ap]n?/sc&j[ap]n?/cht&j[ap]n?/ch&j[ap]n?/tc&j[ap]n?/zh&j[ap]n?/chs&eng?/sc&eng?/cht&eng?/ch&eng?/tc&eng?/zh&eng?/zho?%-cn/zho?%-hans/zho?%-hant/zho?%-hk/zho?%-tw/中日/中英/中上英下/特效/简英/简体&英文/繁英/繁体&英文/繁體&英文/简日/繁日/双语/雙语/简/繁/中/simplified/traditional
