#Port utilisé par webui. Par défaut : 8080
#Accès depuis le réseau local via http://[::1]:port (ipv6) ou ip_de_la_machine:port (ipv4)
port=8060
#Désactiver webui. Par défaut : no
disable=no
#Journaliser les requêtes sur la sortie standard. Par défaut : no
logging=no
#Journaliser sur l'OSD. Par défaut : yes
osd_logging=yes
#Activer l'écoute en ipv4. Par défaut : yes
ipv4=yes
#Activer l'écoute en ipv6. Par défaut : yes
ipv6=no
#Périphériques audio proposés dans le cycle. Laisser vide par défaut pour utiliser toutes les interfaces connues de mpv
#audio_devices=
#Dossier des fichiers statiques du frontal webui. Permet de personnaliser l'interface de webui
#Le chemin indiqué peut être absolu ou relatif. Vide par défaut
#static_dir=
#Chemin du fichier d'authentification. Vide par défaut, voir https://github.com/open-dynaMIX/simple-mpv-webui#htpasswd_path
#Les chemins relatifs sont résolus depuis le dossier de travail courant du programme : préférez donc toujours un chemin absolu
#htpasswd_path=
#Pour utiliser l'API du navigateur de fichiers de base de webui, indiquez ici les chemins absolus des dossiers à exposer (séparés par des ;). Vide par défaut
#Exemple : collections=/home/user/Music;/home/user/Videos
#collections=