###Les commentaires en fin de ligne d'option ne sont pas pris en charge, écrivez-les sur une ligne distincte

##Tenter d'abord de résoudre les url avec ytdl (no par défaut). À adapter selon que la plupart des url lues nécessitent ou non ytdl
try_ytdl_first=yes

##Liste noire des adresses à ne pas résoudre ; format décrit ici : https://mpv.io/manual/master/#options-exclude
##Recommandé avec try_ytdl_first=yes : accélère sensiblement la résolution des adresses réseau
exclude=%.avi$|%.flac$|%.flv$|%.mp3$|%.m3u$|%.m3u8$|%.m4a$|%.m4v$|%.mkv$|%.mp4$|%.ts$|%.VOB$|%.wav$|%.webm$|%.wmw$

##Motifs d'URL que mpv doit tenter de résoudre en priorité avec ytdl lorsque try_ytdl_first vaut no. Même syntaxe que exclude ; l'exemple correspond à la valeur par défaut
include=^%w+%.youtube%.com/|^youtube%.com/|^youtu%.be/|^%w+%.twitch%.tv/|^twitch%.tv/

##https://mpv.io/manual/master/#options-all-formats
#all_formats=no
#force_all_formats=yes

##Autoriser le changement de piste entre les sources (désactivé par défaut pour des raisons de performance)
#use_manifests=no

##yt-dlp, la branche la plus active de youtube-dl, tend à supplanter le projet amont et est très activement développée https://github.com/yt-dlp/yt-dlp/releases
##youtube-dl.exe / yt-dlp.exe doit se trouver dans la variable d'environnement PATH, ou dans le dossier contenant mpv.exe
##Commande de mise à jour de yt-dlp.exe : yt-dlp -U
#ytdl_path=yt-dlp