##Titre du menu des périphériques de sortie audio ; %cursor% et %total% permettent d'afficher la position du curseur et le nombre d'entrées
header=Périphériques audio [%cursor%/%total%]\N------------------------------------
##Style personnalisé de la liste du menu, à l'aide des balises ASS
##Ces styles s'appliquent à toute la liste. Vous devez donc les réinitialiser pour chaque ligne
##Référence des balises ASS : http://docs.aegisub.org/3.2/ASS_Tags/
#global_style={\fnNotoSerifCJKsc-Bold}
header_style={\q2\fnNoto Serif CJK SC\fs30\c&00ccff&}
list_style={\q2\fnNoto Sans Mono CJK SC\fs20\c&Hffffff&}
wrapper_style={\c&00ccff&\fs16}
cursor_style={\c&00ccff&}
selected_style={\c&Hfce788&}
active_style={\c&H33ff66&}
cursor=➤\h
indent=\h\h\h
##Nombre d'entrées affichées par page du menu
num_entries=16
##Activer ou non le défilement circulaire
wrap=yes
##Touches associées lorsque le menu est ouvert
key_move_begin=HOME
key_move_end=END
key_move_pageup=PGUP
key_move_pagedown=PGDWN
key_scroll_down=DOWN WHEEL_DOWN
key_scroll_up=UP WHEEL_UP
key_open_adevice=ENTER MBTN_LEFT
key_close_browser=ESC MBTN_RIGHT