# Emplacement de nircmd.exe ; par défaut, on essaie de l'atteindre via le PATH système. Remarque : dépendance obligatoire
nircmd=nircmd

#Liste des fréquences de rafraîchissement valides, séparées par des points-virgules et classées par ordre croissant
#En ajoutant un trait d'union après un nombre, on peut définir une fréquence d'affichage personnalisée pour cette fréquence vidéo :
# avec "23;24;25-50;60", une vidéo à 25 fps sera affichée à 50 fps
#Cette liste blanche s'applique aussi lors de la restauration de l'affichage : pensez donc à y inclure la fréquence d'origine
#nircmd semble n'accepter que des entiers ; n'utilisez pas de fréquence complète, par exemple 23.976
rates=23;24;25-50;29-59;30-60;50;59;60

#Changer ou non automatiquement la fréquence à la lecture d'un fichier
auto=no

#Durée de pause (en secondes) lors du changement de mode d'affichage
#Mettre 0 pour désactiver la mise en pause de la vidéo
pause=3

#Profondeur de couleur envoyée à nircmd
#Il n'est pas nécessaire de la modifier, c'est juste au cas où
bdepth=32

#Choisir d'utiliser la fréquence d'images estimée ou celle du conteneur
#Voir https://mpv.io/manual/master/#command-interface-container-fps
estimated_fps=no

#Détecter ou non la résolution de l'écran lors du changement automatique de fréquence
#Cette résolution est réutilisée lors de la restauration
detect_display_resolution=yes

#Largeur et hauteur à utiliser lors du changement et de la restauration de la fréquence
#Actif uniquement quand detect_display_resolution vaut no
original_width=1920
original_height=1080

#Si cette valeur est différente de zéro, le script restaurera toujours cette fréquence
#Cela contourne la liste blanche habituelle : assurez-vous donc qu'elle est valide
#La fréquence d'origine réelle sera ignorée
original_rate=0

#Une fois activé, ce mode règle le moniteur sur les dimensions indiquées quand la résolution de la vidéo est supérieure ou égale au seuil
#Si elle est inférieure au seuil, le moniteur est réglé sur les valeurs par défaut ci-dessus ou sur la résolution actuelle
#Cette fonction n'est vraiment utile que si vous ne voulez pas mettre la vidéo à l'échelle en UHD tout en lisant les fichiers UHD dans leur résolution d'origine
UHD_adaptive=no
UHD_threshold=1440
UHD_width=3840
UHD_height=2160

#Afficher ou non les messages d'état sur l'OSD
osd_output=yes