#Taille de police de la palette de commandes, valeur par défaut : 16
font_size=26
#Mettre ou non la taille de police à l'échelle de la fenêtre, valeur par défaut : no
scale_by_window=yes
#Nombre d'entrées affichées dans la palette de commandes, valeur par défaut : 12
lines_to_show=12
#Mettre ou non la lecture en pause à l'ouverture de la palette de commandes, valeur par défaut : no
pause_on_open=yes