###Les commentaires en fin de ligne d'option ne sont pas pris en charge : il faut passer à la ligne

#Langue utilisée par le script pour ses messages sur l'OSD ; eng=anglais, chs=chinois. Valeur par défaut : eng
language=chs
#Avec yes, dynaudnorm est activé par défaut ; valeur par défaut : no
start_keys_enabled=no
#Touche pour entrer dans le mode drcbox ou en sortir
key_toggle_bindings=ALT+n
#Touche pour activer/désactiver le filtre dynaudnorm
key_toggle_drcbox=ALT+N
#Touche pour réinitialiser les réglages du filtre dynaudnorm
key_reset_drcbox=ALT+CTRL+n