enabled=yes
## Profondeur de recherche maximale des chemins, valeur par défaut : 1
max_search_depth=1
## Le script ignore les chemins dont le nombre de répertoires dépasse cette valeur, valeur par défaut : 10
#discovery_threshold=10
## Chemins des disques partagés (montés) à ignorer. Exemple Windows : excluded_dir=["X:", "Z:", "F:/Download/", "Download"]
#excluded_dir=[]