# Fichier de configuration par défaut pour le liage de segments de mpv
# Concerne : https://github.com/CogentRedTester/mpv-segment-linking

# Charger les informations de segments depuis le métafichier indiqué au lieu de les rechercher
metafile=

# Revenir au métafichier de segments par défaut si le fichier courant ne peut pas être lu
fallback_to_metafile=yes

# Métafichier de segments par défaut : le script cherchera un fichier portant ce nom
# dans le répertoire du fichier courant
default_metafile=.segment-linking