#######################################################
## Configuration par défaut de mpv-sub-select        ##
## https://github.com/CogentRedTester/mpv-sub-select ##
#######################################################

# Forcer l'activation du script
#! Remarque : cela ne prend pas le pas sur une valeur explicitement donnée à l'option sid
force_enable=yes

# Sélection expérimentale de la piste audio d'après le fichier json de préférences
select_audio=no

#Surveiller les changements de piste audio et resélectionner les sous-titres quand alang change
observe_audio_switches=yes

# Ne sélectionner que les sous-titres forcés explicitement signalés comme tels dans la piste.
# Par défaut, lors de la recherche d'une piste de sous-titres dans une langue donnée,
# les sous-titres forcés font partie des résultats au même titre que les autres pistes.
# Il n'y a donc aucun moyen d'écrire une règle qui exclue spécifiquement les pistes de sous-titres forcés.
# En activant cette option, un sous-titre forcé ne sera jamais choisi, sauf si une règle inclut explicitement « forced » dans `slang`
explicit_forced_subs=no

# Dossier contenant le fichier « sub-select.json »
config=~~/script-opts