##Titre du menu de la liste des pistes ; %cursor% et %total% affichent la position du curseur et le nombre d'éléments
header=Liste des pistes [%cursor%/%total%]\N------------------------------------
##Personnalisation du style de la liste avec des balises ASS
##Ces styles s'appliquent à toute la liste ; réinitialisez-les donc sur chaque ligne
##Référence des balises ASS : http://docs.aegisub.org/3.2/ASS_Tags/
#global_style={\fnNoto Sans Mono CJK SC}
header_style={\q2\fnNoto Serif CJK SC\fs30\c&00ccff&}
list_style={\q2\fnNoto Sans Mono CJK SC\fs20\c&Hffffff&}
wrapper_style={\c&00ccff&\fs16}
cursor_style={\c&00ccff&}
selected_style={\c&Hfce788&}
active_style={\c&H33ff66&}
cursor=➤\h
indent=\h\h\h
##Nombre d'éléments affichés par page
num_entries=16
##Nombre maximal de caractères affichés avant de tronquer un nom trop long. Valeur par défaut : 100
max_title_length=100
##Activer le défilement en boucle
wrap=yes
##Touches actives lorsque le menu est ouvert
key_move_begin=HOME
key_move_end=END
key_move_pageup=PGUP
key_move_pagedown=PGDWN
key_scroll_down=DOWN WHEEL_DOWN
key_scroll_up=UP WHEEL_UP
key_select_track=ENTER MBTN_LEFT
key_reload_track=F5 MBTN_MID
key_remove_track=DEL BS
key_close_browser=ESC MBTN_RIGHT