# Activer le suivi de visionnage trakt. Valeur par défaut : yes
enabled=no
# Chemin d'enregistrement du fichier de configuration trakt, absolu ou relatif. Valeur par défaut : ~~/trakt_config.json
# Utilisez '/:dir%script%' pour désigner le dossier du script
# Utilisez '/:var' pour désigner une variable d'environnement, par exemple '/:var%APPDATA%' ou '/:var%HOME%'
congfig_path=~~/files/trakt_config.json
# Chemin du fichier d'historique trakt, absolu ou relatif. Valeur par défaut : ~~/trakt_history.json
# Modifiez le contenu du fichier pour corriger une association trakt erronée
history_path=~~/files/trakt_history.json
# Nombre maximal de caractères affichés avant de tronquer un nom trop long. Valeur par défaut : 100
max_title_length=100
# client_id et client_secret à utiliser avec l'API trakt : https://trakt.tv/oauth/applications
# Ils doivent également être encodés en base64
client_id=MmU5ZDg5MDcyYmIxNThlZWZhZmNlNTA5ZjZiMWJmMzM3MzcwMTQwMDU4ODFlZGZiYjgzZWI3ZGRkMWMwNGY1YQ==
client_secret=MDcxYTUzZTVkZDhkODA1NTM2MTU2YWNlZTJjYjU5Njc5YjUwOTAwZWU3YmZkYmVmMTZiNGZmODdkMzQ2NGFiNg==
# URI de redirection OAuth2 ; elle doit correspondre à celle définie dans l'application
redirect_uri=https://zapp.com